### ISSUE TITLE
Controlling which threads the event gets posted to

### ISSUE THREAD

**Issue by creativepsyco** [square/otto#108]
Currently, Otto enforces the Thread level restrictions on the entire bus. But let's say if I want to post my events from a different thread to a different thread, is there support for that? 

Currently I am overriding the `post` method of the Bus to make sure all events are posted on the main thread. This lets my background threads also use the same bus with the guarantee that events shall be posted to the main thread. Are there any potential issues there? Or is there some built-in support for this?

Oh I just read #72 and I agree on Otto's approach but will there be any repercussions if I subclass `Bus.post` and use a Thread-Aware implementation to fire events only on the main thread. Sometimes the Network response will attempt to update the UI by firing an Event which can only be on the main thread.

**Comment by JakeWharton** [comment]
We'll probably just track what Guava does. They're looking at annotation-based `Executors` last I checked. This could be easily accomplished with that mechanism.

**Comment by creativepsyco** [comment]
Currently I am subclassing Otto's event bus and explicitly allowing event
producers to choose which thread to post the event to. I only handle either
Main thread or ANY thread in which case I don't care about the thread it
gets posted to.

On Thu, Jan 8, 2015 at 5:19 PM, Jake Wharton <notifications@github.com>
wrote:

> We'll probably just track what Guava does. They're looking at
> annotation-based Executors last I checked. This could be easily
> accomplished with that mechanism.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/otto/issues/108#issuecomment-69154232>.
>



-- 
Mohit Singh KANWAL (Mr)

[image: Facebook] <http://facebook.com/mohitkanwal>  [image: Twitter]
<http://twitter.com/mohitkanwal>

**Comment by JakeWharton** [comment]
At this time, we have no plans for adding this feature to Otto.
