### ISSUE TITLE
Event subscription on Activity not fired on post from a Service in a different module.

### ISSUE THREAD

**Issue by emanzanoengisoft** [square/otto#120]
Hi, I was trying to extract some of the code from my project into a module/library (a Service and some other classes), but when I try to notify an Activity of my main module (where the views resides) from my Service it seems like the bus is not finding the subscription to deliver the event.

I don't know if I misunderstood Otto's way of delivering events between threads, but I think the Service and the Activity are running on UI's thread, Service is receiving correctly the events posted from the Activity but not at the reverse case.

I think that the service residing in a different module (and package) than the Activity is the reason why I can't receive events on Activities, but I don't know why is happening.

Can someone please explain me the cause of this? Maybe it can be a bug.

**Comment by JakeWharton** [comment]
If the service was in a different process it wouldn't work. Post if you still have issues (after a year...).
