### ISSUE TITLE
Api Request to detect is the object has already registered with the bus: isRegistered()

### ISSUE THREAD

**Issue by saurabytes** [square/otto#137]
Any object should be able to query the bus of its registration status.
If registered it should return true else false.
This would be really handy in avoiding multiple registration and unregistration calls.

**Comment by JakeWharton** [comment]
How are you registering such that you don't know if something happens
multiple times? That's usually an indication you are doing something wrong.

**Comment by saurabytes** [comment]
That's right, I was doing something wrong which I fixed later. But having an api to see if already registered wood avoid such scenarios

**Comment by JakeWharton** [comment]
The right thing to do here is probably throw an exception. I'm surprised it
doesn't, actually.

**Comment by necronet** [comment]
How did you register the object more than once? I've tried that (by mistake) and throws an exception!

**Comment by saurabytes** [comment]
In a static instance of a event handler. The activity asked to register twice and there was no exception.
