### ISSUE TITLE
Bus shouldn't allow an object to be registered twice

### ISSUE THREAD

**Issue by saurabytes** [square/otto#138]
I have an object which registers to a bus for events. I had added the register call at wrong place which ended up registering itself multiple times. Hence receiving duplicate events from the bus.
This shouldn't be allowed. The bus shouldn't register in second and onward calls.

**Comment by necronet** [comment]
As far as I know otto does not allow to double register an object can you be more specific?  can you provide an example?

**Comment by saurabytes** [comment]
I my activity i registered to a bus and forgot to unregister(by mistake). Later when that actiivity was created again it got registered again and so on so forth. This ended up in receiving multiple events(as many times the activity was created) in the handler.
