### ISSUE TITLE
Logging for Otto

### ISSUE THREAD

**Issue by clackbib** [square/otto#144]
Hello,

I'm working on a project that sometimes relies very heavily on would it be possible to expose a setter which lets us provide a logger implementation, and:

1) Logs data whenever an event is posted
2) Logs data when a subscribed method is executed.

Doesn't have to be tied to logging also. Could be a simple callback:

onEventPosted(String eventName, Object eventPosted)

onMethodFired(Object receivedEvent , String ... paramsNames)

Or something similar.

**Comment by JakeWharton** [comment]
You can already do 1 by subscribing to `Object`. I'm not really sure we want to add 2. Why do you care about this information?

**Comment by clackbib** [comment]
Mainly for debugging purposes.
Otto-plugin can help when keeping track/ debugging a project that relies on otto, but a project I work on is pretty big, and I feel like having base logging for this could help getting rid of unwanted/unused subscribes.

I wen ahead and implemented what i think is a possible solution: 
435dfe762fe81803ac77472d3406640e8dd0039a
Not necessarily the best one, but im having trouble getting it to run with maven. Is there any reason the project hasn't been ported to gradle?

**Comment by JakeWharton** [comment]
> Is there any reason the project hasn't been ported to gradle?

Because Maven works fine.

**Comment by JakeWharton** [comment]
All I see from that diff is you reformatted the entire file and thus masked any changes you made.

**Comment by clackbib** [comment]
Code formatting makes it look like I changed a lot more that what is actually different, sorry

**Comment by clackbib** [comment]
Fixing right now

**Comment by clackbib** [comment]
Here:
806c5483b93f8236722ef4eb8b6219e7ad1edd4c

**Comment by JakeWharton** [comment]
The logging would have to be tied to an instance, not static. In general, we're not going to add something like this for two reasons:

 * You can already accomplish most of it by subscribing to `Object` which allows you to see every event.
 * Otto is based on [Guava](https://github.com/google/guava)'s EventBus and we'd like to stay relatively in sync conceptually and semantically (although we obviously deviate a bit here for Android use). If you can get them to add logging, we'd add it here.
