### ISSUE TITLE
Data getting mixed when using Otto in a ViewPager

### ISSUE THREAD

**Issue by JithinSunny** [square/otto#146]
I am using Otto to get result to a fragment when an http request is made successfully.

In my application I have a viewpager. And because the pages are very similar, I use the same fragments in viewpager with different data, to download data.

The fragment methods looks like

     @Override
    public void onResume() {
    super.onResume();
    MMApp.getBus().register(this);
    }

    @Override
    public void onPause() {
    super.onPause();
    MMApp.getBus().unregister(this);
    }

    @Subscribe
      public void onHttpResponseReceived(VolleySuccesObject results) {
     }
 
The data getting mixed, for example the result in page one is showing in page two also

**Comment by JakeWharton** [comment]
An event bus is a publish-subscribe mechanism which means that everyone who is listening to a type (in this case `VolleySuccessObject`), is going to see the same events. If you want to only listen to the result for a specific page, you shouldn't use an event bus or wrap the result in an object that knows which page it is destined for and check that value in the subscriber.
