### ISSUE TITLE
Posted event during rotation

### ISSUE THREAD

**Issue by Michenux** [square/otto#147]
Hi,

I would like to known how you handle events that are produced during rotation phase.
Let's take this scenario :
1- Activity instance "1" registers to the bus in onCreate
2 - User starts a background service from this activity.
3 - User rotates the screen
4 - Activity instance "1" unregisters from the bus in onDestroy
5 - Background service produces a event.
6 - Activity instance "2" registers to the bus in onCreate

What happens to the produced event ?
How activity instance "2" can receive this event ?

Thanks
Laurent.

**Comment by egor-n** [comment]
The event produced in 5 is fired but no one is listening to it, so basically, nothing happens - activity instance "2" doesn't know about the event from 5.

To solve this problem you can use `@Produce` annotation. Read more about it [here](http://square.github.io/otto/) in the "Producing" section.

Essentially it goes like this:
1. cache somewhere your data right before 5
2. a method annotated with `@Produce` should return this data
3. once activity instance "2" registers it immediately receives an event identical to event in 5.

**Comment by JakeWharton** [comment]
Events are inherently transient. If you cannot afford for an event to be missed you need another mechanism in place.
