### ISSUE TITLE
Android Wear

### ISSUE THREAD

**Issue by ZkHaider** [square/otto#156]
Are there any issues regarding Otto use in Android Wear?

**Comment by JakeWharton** [comment]
No? Otto is just a glorified map of event classes to a list of subscribers. It will work on Android and on Wear but not between the two.

**Comment by ZkHaider** [comment]
Right thanks a lot Jake, I found another library here: https://github.com/tajchert/BusWear

I was wondering why there was a specific library only for Wear. Thought maybe there is an issue with current libraries? 

Thanks a lot for letting me know so quickly, I use otto quite a lot in Android, want to see how it will perform for sending and receiving sensor data within the wear module.

**Comment by JakeWharton** [comment]
That lets events go from the phone to the wearable device which is a whole
different thing that we don't support.

**Comment by ZkHaider** [comment]
Right makes sense, I might actually end up using that then. Are you going to support that in the future?

**Comment by JakeWharton** [comment]
Very unlikely. There's very different semantics for cross-device
communication.
