### ISSUE TITLE
Gradle: Failed to resovle

### ISSUE THREAD

**Issue by vijaemanlapaz** [square/otto#159]
Hi im having issue adding this as an dependency.
gradle returns an error "Failed to resolve"

here is my gradle script:

    repositories {
    mavenCentral()
    }

    dependencies {
    compile 'com.squareup:otto:1.3.8'
    }

**Comment by JakeWharton** [comment]
It's definitely there: http://search.maven.org/#artifactdetails%7Ccom.squareup%7Cotto%7C1.3.8%7Cjar

Paste the full output (potentially with `--stacktrace`). This is a Gradle usage question unrelated to Otto, though, which is usually more appropriate on a forum like StackOverflow where _many_ more people have a change to see and answer.
