### ISSUE TITLE
Pass big ArrayList<Object> from service to fragment issue 

### ISSUE THREAD

**Issue by ungvas** [square/otto#162]
Hi, 

i have a service that generate data and pass an ArrayList to Fragment.
For example i pass arrayList with 1000 items but in fragment i get a list with 2 items ((. Maybe the problem is in my service.

I want to know that is possible to pass big lists with otto? 

Thanks ))

**Comment by JakeWharton** [comment]
Size is not relevant to Otto. Object references are passed and they are always the same size, regardless of the object size.
