### ISSUE TITLE
Q: post and subscribe in the same class

### ISSUE THREAD

**Issue by marioosh-net** [square/otto#163]
Is something wrong with posting events and subscribe in the same class ? I have some issue with this approach: subscribed method called multiple times, but one event posted.

```
class Klass {
   void someMethod() {
     bus.post(new SomeEvent());
   }
   @Subscribe
   public void onSomeEvent(SomeEvent e) {
   }
}
```

**Comment by JakeWharton** [comment]
This is perfectly fine (if only a tiny bit strange). There should be no issues.

**Comment by imminent** [comment]
`bus.post(new SomeEvent())` is functionally equivalent to `onSomeEvent(new SomeEvent())`, the default behavior for the bus even makes the execution synchronously. If you do have multiple executions then you have something else wrong.
