### ISSUE TITLE
EventBus vs Otto, what do you think ?

### ISSUE THREAD

**Issue by HugoGresse** [square/otto#166]
I'm really enthousiast about Otto because I trust Square Up developements. But EventBus has a comparaison of both library and it appear that EventBus is faster and a have more functionnality (exception Event Producer) see [here](https://github.com/greenrobot/EventBus/blob/master/COMPARISON.md)

I was wondering what you @SquareUp and other developers of this project think about this.

**Comment by motcwang** [comment]
Combine will be better！

**Comment by HugoGresse** [comment]
as Otto is now deprecated, I can close this issue I think.
