### ISSUE TITLE
Events & inheritance

### ISSUE THREAD

**Issue by oradkovsky** [square/otto#167]
This is somewhat similar to https://github.com/square/otto/issues/122  but still different to me:

Let's say we have base class like this (LogicEvent details irrelevant)
```
public abstract class CommonLogic {
    public abstract void execute();

    public class Success extends LogicEvent {
    }
}
```
If, say, I've got class A inherited from CommonLogic, as well as class B, then if I have @subscribe methods A.Success or B.Success, they will all be triggered if I post new A.Succes() or new B.Success(). Can I avoid such behavior? Is this behavior by design? Thanks.

**Comment by JakeWharton** [comment]
> they will all be triggered

Yes. They are the same class. It doesn't matter whether you reference it as `A.Success`, `B.Success`, or `CommonLogic.Success` they are all the same class. When you subscribe you are subscribing to the same class, `Success`. If you want different classes, you'll have to create different subclasses of `Success`.
