### ISSUE TITLE
Topic based subscriptions

### ISSUE THREAD

**Issue by erikash** [square/otto#174]
Hi,
I was wondering if topic based subscriptions are on your roadmap?

For example, exchange quote:

Clients can subscribe to get all market quotes:
@Subscribe public void answerAvailable(QuoteRecievedEvent event) {
    // TODO: React to the event somehow!
}

Clients can subscribe to get part of the market quotes:
otto.setTopics(this, QuoteRecievedEvent, "AAPL;GOOG"); // *NOT* proposing an api, just conveying an example.

Thanks,
Erik.

**Comment by JakeWharton** [comment]
We have no plans for this, no. The library is meant for pure publish/subscribe and higher-level operations like filtering and combining are pushed onto the consuming code.

Consumers of events can filter events directly using normal mechanisms of Java:
```java
@Subscribe public void onAnswerAvailable(QuoteReceivedEvent event) {
  if (!"GOOG".equals(event.symbol()) && !"AAPL".equals(event.symbol()) {
    return;
  }
  // Normal event handling code.
}
```

You can also use a mechanisms where filtering is a first-class citizen like RxJava:
```java
ticker.quotes()
    .fitler(q -> "GOOG".equals(q.symbol()) || "APPL".equals(q.symbol()))
    .subscribe(q -> doSomethingWithQuote(q));
```
