### ISSUE TITLE
Can't use okhttp combine with otto?

### ISSUE THREAD

**Issue by jompon** [square/otto#177]
My Gradle
compile 'com.squareup.okhttp:okhttp:2.6.0'
compile 'com.squareup:otto:1.3.8'
```java
public final class BusProvider {
  private static final Bus BUS = new Bus(); <--------Error on this line

  public static Bus getInstance() {
    return BUS;
  }

  private BusProvider() {
    // No instances.
  }
}
```
>java.lang.NoClassDefFoundError: com.squareup.otto.ThreadEnforcer

**Comment by JakeWharton** [comment]
These libraries do not interact. Try a clean build or disable/update your ProGuard config as it might be erroneously stripping classes.

As this is a usage question and not a bug or feature request, StackOverflow is a better place for these types of general questions.
