### ISSUE TITLE
Post event to a service

### ISSUE THREAD

**Issue by 468122151** [square/otto#178]
I post an event to  my service in a singleton instance ,and it works well the first time. But when I try to close the current activity and then  jump to this activity again , the event bus doesn't work, my service receives nothing. Then I try to debug it , and the BusProvider  do post() method. What's the problem?

**Comment by JakeWharton** [comment]
You haven't provided enough information to make this report actionable, but in general it sounds like a usage problem and not an actual library bug. Please post this to StackOverflow with the 'otto' tag, along with more details about exactly what you are doing. This issue tracker is for feature request and bugs in the library itself.

**Comment by 468122151** [comment]
ok thank you
