### ISSUE TITLE
Subscribe after crash

### ISSUE THREAD

**Issue by rusmichal** [square/otto#179]
Hello guys.

I have strange problem. I have simple textView (injected by ButterKnfie) and I have simple method subscribe like this:

```@Subscribe
 public void onPresenceChanged(final ChangeInPresenceEvent event) {
      getActivity().runOnUiThread(new Runnable() {
               @Override
               public void run() {
                        watchingIndicator.setText("How many");
               }
      });
 }
```

I recevied null pointer exeception for TextView. It look like app go crash but something post event and I received event in this method and it will try setText but watchingIndicator is null.

**Comment by JakeWharton** [comment]
This is a usage problem, not an Otto bug. Sounds like you either need a null check or you need to unregister when the UI goes away (or defer registering until the UI is available).

**Comment by JakeWharton** [comment]
If you have further problems, StackOverflow with the 'otto' tag is a much more appropriate place to ask usage questions. There's many more people there helping and it serves as an archive for future people searching for help.
