### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.squareup.otto.ThreadEnforcer

### ISSUE THREAD

**Issue by harshgaba** [square/otto#183]
i'm getting this issue in Bus bus=new Bus(); 
at runtime i'm getting java.lang.NoClassDefFoundError: com.squareup.otto.ThreadEnforcer

i installed otto as per doc on offical website.
it works fine for API level above 19, but below or on API level 19 , app crashes.
don't now how to fix. please resolve or assists.

**Comment by X-Strange** [comment]
I have the same issue, after add GCM to my app. I enabled multiDex compilation to solve 64k issue. 
My dependencies (fragment):
    compile 'com.squareup:otto:1.3.8'//Otto Bus
    compile 'com.squareup.picasso:picasso:2.5.2'//Picasso
    compile('com.squareup.retrofit:retrofit:2.0.0-beta2') {
        exclude module: 'okhttp'
    }
    compile 'com.squareup.okhttp:okhttp:2.5.0' //OkHttp
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2' //Gson
Anyone has an idea how to fix this?

**Comment by nanzee** [comment]
Same problem, looks to be happening only when multiDex is enabled and is only happening on emulator.  No issue on physical device.

**Comment by jjhesk** [comment]
I found this on [stackoverflow](http://stackoverflow.com/questions/28857860/classnotfoundexception-didnt-find-class-android-os-persistablebundle-otto-an) but im not sure if it is the real fix of it.

**Comment by drakeet** [comment]
BTW: Maybe you made a mistake on the onCreate method, the SDK add a new
onCreate method after 21, many people will overwrite the method then made
errors.
世外桃源 <notifications@github.com>于2016年5月13日 周五09:26写道：

**Comment by JakeWharton** [comment]
This class is included in the released jar so any classloading issues will be specific to your app, likely related to multidex.

**Comment by kartiksetia** [comment]
This is because of 64K android method error. you have to add multidex library in your application class .
http://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library
