### ISSUE TITLE
 android.database.sqlite.SQLiteException: no such table

### ISSUE THREAD

**Issue by Kristaps89** [square/otto#201]
public class Visits extends SugarRecord{
           public` int num_visits;
           public int total_visits;
}

Visits visits = Visits.findById(Visits.class,1L);

when run this code,  I got the follow error message.

android.database.sqlite.SQLiteException: no such table: VISITS (code 1): , while compiling: SELECT * FROM VISITS WHERE id=? LIMIT 1

how can I fix it?

**Comment by JakeWharton** [comment]
I think you need to file this on SugarORM instead.

**Comment by Kristaps89** [comment]
Thank you for you reply.

**Comment by Kristaps89** [comment]
I disabled "Instant run", so I can fix this error.

**Comment by JakeWharton** [comment]
This has nothing to do with Otto
