### ISSUE TITLE
Update for Gradle 4 and Bus doesnt work more.

### ISSUE THREAD

**Issue by MarcosiOSdev** [square/otto#202]
Hello everybody

My project was gradle 1.3.0 and Busprovider was work perfectly . 
When I update my project for Gradle 3 because of FCM, My Bus doesnt call @Subscribe and give me "V/FA: Inactivity, disconnecting from the service"

I have two branches : gradle 1.3 and gradle 3, It works on gradle 1.3 when I change to gradle 3 it doesnt work more.

I didnt change the code , I changed only config in build.gradles

I think that is wrong is because of `proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'` and change from `apt `to `annotationProcessor` . My project has very productFlavors.

Can anybody  help me ?

**Comment by Giszmo** [comment]
If you think it's proguard, then please try that out. Deactivate proguard and see if it works. Also the title of your issue does not match the content.

**Comment by JakeWharton** [comment]
The version of Gradle cannot affect the behavior of a library. If you think you have a bug please provide a failing test case or executable sample which demonstrates it. Otherwise we have no idea what's going on.

**Comment by MarcosiOSdev** [comment]
There are some code that I use in my project. 
https://stackoverflow.com/questions/48506769/otto-bus-doesnt-work-when-i-use-post

I only changed the version gradle , it was only thing  I've done !
