### ISSUE TITLE
I can't receive the event

### ISSUE THREAD

**Issue by saebinna** [square/otto#203]
When i use androidAnnotation 3.3.2 and android support appcompat-v7 25.3.1, everything is ok.
But if i update to androidAnnotation 4.3.1 and android support appcompat-v7 26.1.0, i can't receive the event.
Can any one help?

**Comment by JakeWharton** [comment]
This project is no longer actively maintained, but this isn't enough information to determine a cause of the problem. Otto doesn't interact with either of those libraries directly so I have a hard time seeing how they could affect it. Perhaps try posting on StackOverflow?
