### ISSUE TITLE
java.lang.RuntimeException: Could not dispatch event

### ISSUE THREAD

**Issue by ZuJunJun** [square/otto#209]
![image](https://user-images.githubusercontent.com/21032325/51730635-3ad84e80-20b3-11e9-8cbb-9cae54669ef6.png)

**Comment by JakeWharton** [comment]
Sounds like you're using a non-main thread confined bus and touched a view as a result of an event sent from a background thread. Either check and post to the main thread in your subscriber or switch to a main thread bus.
