### ISSUE TITLE
Refreshing the screen (fragment) from another thread

### ISSUE THREAD

**Issue by pommedeterresautee** [square/otto#38]
Hi,
I am using Otto on my application. It works well.

I would be interested in refreshing the screen from an event in an intentservice (which has its own thread).

For that, I am trying to use Otto with ThreadEnforcer.ANY

But I got the same exception that I would obtain if I would call the view directly from the intentService (means other that the main thread). Is there a way in Otto to "redirect" easily the event from the IntentService to the Main thread ??? I just want to know when to do it.

Thank you

Michael

**Comment by Flashbump** [comment]
Looks just perfect. 
What are the drawbacks of such a pattern?
Are there better alternative to propagate a model change in a service back to the ui?
F.

**Comment by juanmendez** [comment]
Lets pretend you have directly used Bus everywhere already, you can use composition over inheritance.

public class BusUtil
{
    private static final Handler mainThread = new Handler(Looper.getMainLooper());

    public static void postOnMain( final Bus bus, final Object event) {

        mainThread.post(new Runnable() {
            @Override
            public void run() {
                bus.post(event);
            }
        });
    }
}

**Comment by Hesamedin** [comment]
what is a best approach to handle `event` parameter in case is `null`? - return from the method in case is null or creating new `object` instead?
