### ISSUE TITLE
Problem using it with AndroidAnnotations

### ISSUE THREAD

**Issue by gdogaru** [square/otto#61]
I tried using dagger with AndroidAnnotations within activities.
The problem is that AndroidAnnotations creates a subclass of my activity.
When you look for annotated subscribers in com.squareup.otto.AnnotatedHandlerFinder#loadAnnotatedMethods you use listenerClass.getDeclaredMethods()
This does not return the methods from the super-class. So I can not receive messages if I create a subclass of the class that contains subscribe methods.
I got around this by registering an anonymous class with an annotated method.
Not sure if you want to support this, just mentioned it.
Thanks,
Gabi

**Comment by JakeWharton** [comment]
#135 will restore hierarchy walking.
