### ISSUE TITLE
Override point dispatch, package protected

### ISSUE THREAD

**Issue by brh** [square/otto#65]
I suppose this is a nit, but Bus.dispatch is declared protected and is said to be an "appropriate override point", but EventHandler has package access.  I could put my class at the squareup level, but that just seems funky.  Can EventHandler be made public?

**Comment by JakeWharton** [comment]
#108 is the solution for this. Guava is looking to implement annotations which map to `Executors` on which the callbacks get run. A `@MainThread` annotation could run on one which wraps the main thread `Handler`. Closing since this issue is now redundant with that one.
