### ISSUE TITLE
Generic producers

### ISSUE THREAD

**Issue by romainpiel** [square/otto#78]
Hey,

I'm moving my app from EventBus to Otto, so far so good.
Concerning Producers, would it be doable to have something like this?

``` Java
public class MyClass<T> {

    T lastEvent;

    @Produce
    public T produceEvent() {
        return lastEvent;
    }

}
```

I just tried and nothing is produced. I understand it might be hard to know the return type but I'd love to have generic producers.

Thanks

**Comment by tentypwtk** [comment]
Any alternatives in 2017 to avoid creating new classes for each event? I'd like to use BusEvent<T> and only get those when using @Subscibe.
